### ISSUE TITLE
Properties not working properly

### ISSUE THREAD

**Issue by JeovaniAgostini** [Bala-raj/react-custom-audio-player#11]
Some of the props like the 'enableDownload' prop are not responding to "true" or "false" conditions. Need some review

**Comment by Bala-raj** [comment]
funny bug, please check now with 1.3.3.

**Comment by JeovaniAgostini** [comment]
Still not working when i try to set the props to true or false at the flag "enableDownload"
Ex: <AudioPlayer enableDownload="true" src={Audio}/> does not shows the download button. Also the download button was suposed to apear by default and is not happening.

**Comment by Bala-raj** [comment]
please check now.

**Comment by JeovaniAgostini** [comment]
Everything is working fine now. Thanks
